Mechanisms to prevent client identification
tireddy2/ohai pull request #26
Opened 2022-08-30 07:23 UTC by tireddy2

2022-09-01 15:00 UTC, boucadair requested changes
very minor edits

2022-09-01 15:00 UTC, boucadair commented on draft-rdb-ohai-feedback-to-proxy-05.xml
> +    <section anchor="mechanism" title="Prevent client identification">
```suggestion
    <section anchor="mechanism" title="Prevent Client identification">
```

2022-09-01 15:00 UTC, boucadair commented on draft-rdb-ohai-feedback-to-proxy-05.xml
> +      <t>The following mechanisms can be used by the Oblivious relay to
```suggestion
      <t>The following mechanisms can be used by an Oblivious relay to
```

2022-09-01 15:00 UTC, boucadair commented on draft-rdb-ohai-feedback-to-proxy-05.xml
> +      process "ohttp-target" parameter with value set to 2 :</t>
```suggestion
      process "ohttp-target" parameter with a value set to '2':</t>
```

2022-09-01 15:00 UTC, boucadair commented on draft-rdb-ohai-feedback-to-proxy-05.xml
> +          rate-limit requests from the offending client for a certain duration
```suggestion
          rate-limit requests from the offending client for a certain duration (that is implementation-specific)
```

2022-09-01 15:00 UTC, boucadair commented on draft-rdb-ohai-feedback-to-proxy-05.xml
> +          <t>The Oblivious relay acts to rate-limit the client provided it has
```suggestion
          <t>The Oblivious relay acts to rate-limit the traffic of the client provided it has
```

2022-09-01 15:00 UTC, boucadair commented on draft-rdb-ohai-feedback-to-proxy-05.xml
> +          a bad reputation score (Many security network security vendors offer
```suggestion
          a bad reputation score (e.g., many security network security vendors offer
```

2022-09-01 15:00 UTC, boucadair commented on draft-rdb-ohai-feedback-to-proxy-05.xml
> +          if the target is misbehaving. For example, if the target is is
```suggestion
          if the target is misbehaving. For example, if the target is
```

2022-09-01 15:00 UTC, boucadair commented on draft-rdb-ohai-feedback-to-proxy-05.xml
> +          ohttp-target parameter set to 2 for these benign clients to identify
```suggestion
          "ohttp-target" parameter set to '2' for these benign clients to identify
```

2022-09-09 01:04 UTC, danwing approved these changes

2022-09-12 06:43 UTC, merged